# Generated by Django 5.1.6 on 2025-02-28 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
