# Generated by Django 5.1.6 on 2025-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_issue_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
